Spree::PrintSettings::Config.set( :print_logo_path => "/images/invoice_logo.png" )
Spree::PrintSettings::Config.set( :print_company_name => "Functional Ergonomics" )
Spree::PrintSettings::Config.set( :print_company_address1 => "2186 Mountain Grove Ave. Suite 405" )
Spree::PrintSettings::Config.set( :print_company_address2 => "Burlington, ON L7P 4X4" )
Spree::PrintSettings::Config.set( :print_company_phone => "(905) 592-1588" )
Spree::PrintSettings::Config.set( :print_company_website => "http://www.functionalergonomics.ca" )